server:
  port: 8787
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apotik?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true